name: Build

on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact 7z
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-7z
          path: release/*/*.7z
          retention-days: 5

      - name: Upload Artifact exe
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-exe
          path: release/*/*.exe
          retention-days: 5